require("syauqeesy.remap")
require("syauqeesy.set")
require("syauqeesy.plugin.telescope")
require("syauqeesy.plugin.treesitter")
require("syauqeesy.plugin.lsp")
require("syauqeesy.plugin.kanagawa")
require("syauqeesy.plugin.nvim-tree")
